project:
  type: book
  output-dir: docs

book:
  title: "Ariel's RS learning diary"
  author: "Qianyu Ren"
  date: "2024/01/18"
  chapters:
    - personal-introduction.qmd
    - intro.qmd
    - summary.qmd
    - index.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

